kind: plan
name: xperia-gameenhancer
description: "Backs up photos from my XPERIA and zips them."
# An array of steps to be executed in order
steps:
  - name: "Pull GameEnhancer Screenshots from phone"
    # Which method to use for this step
    method: adb-pull
    # Provides the values for the variables in the method's command
    params:
      device_id: "QV7703DYJ4"
      source_path: "/storage/emulated/0/Pictures/Screenshots/GameEnhancer/"
      destination_path: "."
  - name: "Pull GameEnhancer Videos from phone"
    # Which method to use for this step
    method: adb-pull
    # Provides the values for the variables in the method's command
    params:
      device_id: "QV7703DYJ4"
      source_path: "/storage/emulated/0/Movies/GameEnhancer/"
      destination_path: "."
  - name: "Compress the pulled photos"
    method: zip-archive-dated
    params:
      archive_path: "."
      archive_name: "GameEnhancer"
      source_dir: "./GameEnhancer"
