kind: plan
name: xperia-photos
description: "Backs up photos from my XPERIA and zips them."
# An array of steps to be executed in order
steps:
  - name: "Pull photos from phone"
    # Which method to use for this step
    method: adb-pull
    # Provides the values for the variables in the method's command
    params:
      device_id: "QV7703DYJ4"
      source_path: "/storage/emulated/0/DCIM/PHOTOGRAPHY_PRO/"
      destination_path: "."
  - name: "Test the pulled photos"
    method: test-media-ffmpeg
    params:
      extension: "JPG"
      source_dir: "./PHOTOGRAPHY_PRO"
  - name: "Test the pulled videos"
    method: test-media-ffmpeg
    params:
      extension: "mp4"
      source_dir: "./PHOTOGRAPHY_PRO"
  - name: "Compress the pulled photos"
    method: zip-archive-linux-dated
    params:
      archive_path: "."
      archive_name: "PHOTOGRAPHY_PRO"
      source_dir: "./PHOTOGRAPHY_PRO"
  - name: "Test the compressed archive"
    method: test-media-7z
    params:
      filepath: "./PHOTOGRAPHY_PRO-$(date -u '+%y%m%d').zip"
