kind: plan
name: xperia-gameenhancer
description: "Backs up photos from my XPERIA and zips them."
steps:
  - name: "Pull GameEnhancer Screenshots from phone"
    method: adb-pull
    params:
      device_id: "QV7703DYJ4"
      source_path: "/storage/emulated/0/Pictures/Screenshots/GameEnhancer/"
      destination_path: "."
  - name: "Pull GameEnhancer Videos from phone"
    method: adb-pull
    params:
      device_id: "QV7703DYJ4"
      source_path: "/storage/emulated/0/Movies/GameEnhancer/"
      destination_path: "."
  - name: "Verify GameEnhancer Screenshots"
    method: test-media-ffmpeg
    params:
      source_dir: "./GameEnhancer/*"
      extension: "png"
  - name: "Verify GameEnhancer Records"
    method: test-media-ffmpeg
    params:
      source_dir: "./GameEnhancer/*"
      extension: "mp4"
  - name: "Compress the pulled photos"
    method: zip-archive-linux-dated
    params:
      archive_path: "."
      archive_name: "GameEnhancer"
      source_dir: "./GameEnhancer"
