kind: method
name: test-media-ffmpeg
description: "Checks for corruption in media files using ffmpeg."
command: |
  for file in {{source_dir}}/*.{{extension}}; do
      echo "Testing: $file"
      # Check for actual corruption (not just timestamp warnings)
      if ffmpeg -v fatal -i "$file" -f null - 2>&1 | grep -q .; then
          echo "  ✗ SERIOUS ERROR"
      else
          echo "  ✓ Playable (timestamp warnings only)"
      fi
  done
